(() => {
  const host = document.querySelector('.product-screen');
  if (!host) return;
  const board = document.createElement('div');
  board.className = 'preview-board';
  host.append(board);
  const metric = (label,value,unit='') => `<div class="preview-metric"><span>${label}</span><strong>${value}</strong><small>${unit}</small></div>`;
  const card = (title,subtitle,content) => `<section class="preview-card"><h5>${title}</h5><p>${subtitle}</p>${content}</section>`;
  const bars = rows => `<div class="preview-bars">${rows.map(([label,value])=>`<div class="preview-bar"><span>${label}</span><i><b style="width:${value}%"></b></i><span>${value}</span></div>`).join('')}</div>`;
  const line = (personal=false) => `<svg viewBox="0 0 500 145" role="img" aria-label="${personal?'Example personal energy history with daily variation':'Example energy and mood trends over four weeks'}"><path class="chart-grid" d="M30 15H480M30 60H480M30 105H480"/><text x="0" y="19">100</text><text x="6" y="64">50</text><text x="13" y="109">0</text><path class="chart-fill" d="${personal?'M30 42 L65 41 L100 47 L135 43 L170 64 L205 67 L240 24 L275 101 L310 106 L345 79 L380 111 L415 45 L450 56 L480 83':'M30 76 C75 65 100 65 140 75 S205 57 255 60 S325 53 365 56 S435 48 480 44'} L480 110 L30 110Z"/><path class="chart-line" d="${personal?'M30 42 L65 41 L100 47 L135 43 L170 64 L205 67 L240 24 L275 101 L310 106 L345 79 L380 111 L415 45 L450 56 L480 83':'M30 76 C75 65 100 65 140 75 S205 57 255 60 S325 53 365 56 S435 48 480 44'}"/>${personal?'':'<path d="M30 81 C75 70 100 70 140 80 S205 65 255 65 S325 60 365 61 S435 54 480 50" fill="none" stroke="#efd06b" stroke-width="2"/>'}<text x="30" y="138">${personal?'11 Jul':'Week 1'}</text><text x="170" y="138">${personal?'21 Jul':'Week 2'}</text><text x="310" y="138">${personal?'31 Jul':'Week 3'}</text><text x="448" y="138">${personal?'8 Aug':'Week 4'}</text></svg>`;
  const columns = `<svg viewBox="0 0 500 145" role="img" aria-label="Example energy scores by department"><path class="chart-grid" d="M20 20H490M20 65H490M20 110H490"/>${[['Engineering',74],['Design',61],['Sales',68],['Marketing',57],['Ops',74],['Support',69]].map(([n,v],i)=>`<rect x="${30+i*77}" y="${110-v}" width="48" height="${v}" rx="4" fill="${i%4===0?'#88cca5':'#ac92f5'}"/><text x="${54+i*77}" y="134" text-anchor="middle" style="font-size:9px">${n}</text>`).join('')}</svg>`;
  const donut = `<div class="preview-donut"><div class="preview-donut-ring" role="img" aria-label="Example distribution: 39 percent low, 21 percent medium, 39 percent high risk; rounded"></div><div class="preview-legend"><span><i style="background:#88cca5"></i>Low · 39%</span><span><i style="background:#efd06b"></i>Medium · 21%</span><span><i style="background:#b097f8"></i>High · 39%</span></div></div>`;
  const insights = `<div class="preview-insight"><strong>Energy pattern</strong><p>Notice changes over time and make space for recovery.</p></div><div class="preview-insight"><strong>A useful next step</strong><p>Use your reflection to guide a conversation when you choose.</p></div>`;
  const people = `<div class="preview-people">${[['Engineering',60,'High'],['People',58,'High'],['Marketing',50,'High'],['Operations',48,'Med']].map(([name,value,risk])=>`<div class="preview-person"><span>${name}</span><i><b style="width:${value}%"></b></i><small>${risk}</small></div>`).join('')}</div>`;
  const data = {
    employee:{title:'Your wellbeing, in focus',sub:'A private space to check in and see your patterns.',badge:'Private to you',metrics:[['Energy today','75','/ 100'],['Feeling','Great',''],['View','30','days'],['Check-in','Saved','']],cards:[card('Energy history','Your personal pattern · Last 30 days',line(true)),card('Today’s check-in','Take a moment for yourself',`<div class="preview-checkin"><span>Your energy today</span><strong>75</strong></div><div class="preview-energy"></div><div class="preview-moods"><span>Great</span><span>Good</span><span>Okay</span><span>Low</span></div>`),card('Personal insights','Small signals, useful reflection',insights),card('Your next steps','Support on your terms',`<div class="preview-insight"><strong>Wellbeing objectives</strong><p>Choose a personal focus and keep track of what helps.</p></div><div class="preview-insight"><strong>Private reflections</strong><p>Your notes stay yours unless you choose to share.</p></div>`)],foot:'Your reflection. Your choice to share.'},
    manager:{title:'Team patterns, clearly',sub:'Reports & analytics · Aggregated team signals.',badge:'Last 30 days',metrics:[['Total employees','28',''],['Average energy','68','/ 100'],['Survey participation','68','%'],['Recognition','947','']],cards:[card('Energy & mood trend','Last 30 days · All departments',line()),card('Attrition risk','Distribution across departments',donut),card('Energy by department','Directional scores · Shared context',columns),card('Risk breakdown','Share of the team',bars([['Low risk',39],['Medium risk',21],['High risk',39]]))],foot:'Aggregated insight. Human judgement.'},
    admin:{title:'Workforce risk, in context',sub:'Company overview · Signals to support earlier conversations.',badge:'Company view',metrics:[['Critical risk','0',''],['High risk','5',''],['Medium risk','38',''],['Low risk','14','']],cards:[card('Risk by department','Average directional risk score',bars([['Finance',61],['People',49],['Operations',46],['Sales',37],['Marketing',32]])),card('Risk distribution','57 employees · Current snapshot',`<div class="preview-donut"><div class="preview-donut-ring" style="background:conic-gradient(#88cca5 0 24.6%,#efd06b 24.6% 91.3%,#a994f5 91.3%);--total:57" role="img" aria-label="14 low, 38 medium and 5 high risk"><span style="position:absolute;z-index:1;inset:0;display:grid;place-items:center;font-size:26px;background:#1b1e29;margin:21px;border-radius:50%">57</span></div><div class="preview-legend"><span><i style="background:#88cca5"></i>Low · 14</span><span><i style="background:#efd06b"></i>Medium · 38</span><span><i style="background:#a994f5"></i>High · 5</span></div></div>`),card('Signals for review','Example team signals · Add context before action',people),card('Decision support','Governance stays visible',`<div class="preview-insight"><strong>Start with a conversation</strong><p>Signals inform a conversation. They are never the sole basis for a people decision.</p></div><div class="preview-insight"><strong>Role-based visibility</strong><p>Access follows each role’s authority.</p></div>`)],foot:'Context before conclusions.'}
  };
  const render = key => {
    const item=data[key]||data.employee;
    board.dataset.role=key;
    board.innerHTML=`<div class="preview-heading"><div><h4>${item.title}</h4><p>${item.sub}</p></div><span class="preview-badge">${item.badge}</span></div><div class="preview-metrics">${item.metrics.map(m=>metric(...m)).join('')}</div><div class="preview-charts">${item.cards.join('')}</div><div class="preview-foot"><span class="preview-signal">${item.foot}</span><span>Illustrative preview · Example data</span></div>`;
  };
  document.querySelectorAll('[data-product-view]').forEach(tab=>tab.addEventListener('click',()=>render(tab.dataset.productView)));
  // Selection can also change through the tablist's keyboard controls.
  new MutationObserver(()=>render(document.querySelector('[data-product-view][aria-selected="true"]')?.dataset.productView||'employee')).observe(document.querySelector('.role-rail'),{attributes:true,subtree:true,attributeFilter:['aria-selected']});
  render('employee');
  document.querySelector('[data-product-expand]').textContent='Original screen ↗';
  document.querySelector('.product-note').textContent='Adapted interface previews with illustrative data. Open the original development screen to explore the source interface.';
  const interbeingPanel = document.querySelector('.bridge-mark');
  if (interbeingPanel) {
    interbeingPanel.classList.add('bridge-link');
    const interbeingLink = document.createElement('a');
    interbeingLink.className = 'bridge-card-link';
    interbeingLink.href = 'https://interbeingleadership.com/';
    interbeingLink.setAttribute('aria-label', 'Explore the InterBeing website');
    interbeingLink.innerHTML = '<span class="bridge-corner" aria-hidden="true">↗</span>';
    interbeingPanel.append(interbeingLink);
  }
})();
